sbt-transforms: Add missing includes for LLVM 10
This commit should not affect compilation with
older LLVM versions in any way.

Fixes usage of llvm::cl:opt.

...
[  7%] Building CXX object CMakeFiles/LLVMsbt.dir/CheckModule.cpp.o
/root/symbiotic/transforms/CheckModule.cpp:17:8: error: ‘cl’ does not name a type
   17 | static cl::opt<std::string> detect_calls("detect-calls",
      |        ^~
/root/symbiotic/transforms/CheckModule.cpp: In member function ‘virtual bool CheckModule::runOnModule(llvm::Module&)’:
/root/symbiotic/transforms/CheckModule.cpp:42:8: error: ‘detect_calls’ was not declared in this scope; did you mean ‘detected_call’?
   42 |   if (!detect_calls.empty()) {
      |        ^~~~~~~~~~~~
      |        detected_call
/root/symbiotic/transforms/CheckModule.cpp:55:11: error: ‘errs’ is not a member of ‘llvm’
   55 |     llvm::errs() << "Found call to function " << detect_calls << "\n";
      |           ^~~~
/root/symbiotic/transforms/CheckModule.cpp:55:50: error: ‘detect_calls’ was not declared in this scope; did you mean ‘detected_call’?
   55 |     llvm::errs() << "Found call to function " << detect_calls << "\n";
      |                                                  ^~~~~~~~~~~~
      |                                                  detected_call
/root/symbiotic/transforms/CheckModule.cpp:59:11: error: ‘errs’ is not a member of ‘llvm’
   59 |     llvm::errs() << "Found a call via pointer\n";
      |           ^~~~
/root/symbiotic/transforms/CheckModule.cpp: In member function ‘void CheckModule::runOnFunction(llvm::Function&)’:
/root/symbiotic/transforms/CheckModule.cpp:75:39: error: ‘detect_calls’ was not declared in this scope; did you mean ‘detected_call’?
   75 |             if (F->getName().str() == detect_calls) {
      |                                       ^~~~~~~~~~~~
      |                                       detected_call
...
[ 46%] Building CXX object CMakeFiles/LLVMsbt.dir/ReplaceUBSan.cpp.o
/root/symbiotic/transforms/ReplaceUBSan.cpp:34:7: error: ‘cl’ in namespace ‘llvm’ does not name a type
   34 | llvm::cl::opt<bool> justRemove("replace-ubsan-just-remove",
      |       ^~
/root/symbiotic/transforms/ReplaceUBSan.cpp:38:7: error: ‘cl’ in namespace ‘llvm’ does not name a type
   38 | llvm::cl::opt<bool> keepShifts("replace-ubsan-keep-shifts",
      |       ^~
/root/symbiotic/transforms/ReplaceUBSan.cpp: In member function ‘virtual bool {anonymous}::ReplaceUBSan::runOnFunction(llvm::Function&)’:
/root/symbiotic/transforms/ReplaceUBSan.cpp:81:13: error: ‘justRemove’ was not declared in this scope
   81 |         if (justRemove && (!keepShifts || !isshift)) {
      |             ^~~~~~~~~~
/root/symbiotic/transforms/ReplaceUBSan.cpp:81:29: error: ‘keepShifts’ was not declared in this scope
   81 |         if (justRemove && (!keepShifts || !isshift)) {
      |                             ^~~~~~~~~~
...
[ 65%] Building CXX object CMakeFiles/LLVMsbt.dir/InstrumentNontermination.cpp.o
/root/symbiotic/transforms/InstrumentNontermination.cpp:24:7: error: ‘cl’ in namespace ‘llvm’ does not name a type
   24 | llvm::cl::opt<bool> insertHeader("instrument-nontermination-mark-header",
      |       ^~
/root/symbiotic/transforms/InstrumentNontermination.cpp: In member function ‘bool InstrumentNontermination::instrumentLoop(llvm::Loop*, const std::set<llvm::Value*>&)’:
/root/symbiotic/transforms/InstrumentNontermination.cpp:242:9: error: ‘insertHeader’ was not declared in this scope
  242 |     if (insertHeader) {
      |         ^~~~~~~~~~~~