sbt-transforms: Rewrite ClassifyInstructions using FunctionPass
BasicBlockPass has been declared as deprecated and its definition
is not shipped with LLVM 10 (at least on Fedora).

See: https://llvm.org/doxygen/classllvm_1_1BasicBlockPass.html

Fixes:

[ 90%] Building CXX object CMakeFiles/LLVMsbt.dir/ClassifyInstructions.cpp.o
/root/symbiotic/transforms/ClassifyInstructions.cpp:22:47: error: expected class-name before ‘{’ token
   22 |   class ClassifyInstr : public BasicBlockPass {
      |                                               ^
/root/symbiotic/transforms/ClassifyInstructions.cpp:78:12: error: ‘bool {anonymous}::ClassifyInstr::runOnBasicBlock(llvm::BasicBlock&)’ marked ‘override’, but does not override
   78 |       bool runOnBasicBlock(BasicBlock &B) override {
      |            ^~~~~~~~~~~~~~~
/root/symbiotic/transforms/ClassifyInstructions.cpp: In constructor ‘{anonymous}::ClassifyInstr::ClassifyInstr()’:
/root/symbiotic/transforms/ClassifyInstructions.cpp:76:25: error: class ‘{anonymous}::ClassifyInstr’ does not have any field named ‘BasicBlockPass’
   76 |       ClassifyInstr() : BasicBlockPass(ID) {}
      |                         ^~~~~~~~~~~~~~
In file included from /usr/include/llvm/Pass.h:316,
                 from /root/symbiotic/transforms/ClassifyInstructions.cpp:14:
/usr/include/llvm/PassSupport.h: In instantiation of ‘llvm::Pass* llvm::callDefaultCtor() [with PassName = {anonymous}::ClassifyInstr]’:
/usr/include/llvm/PassSupport.h:95:28:   required from ‘llvm::RegisterPass<passName>::RegisterPass(llvm::StringRef, llvm::StringRef, bool, bool) [with passName = {anonymous}::ClassifyInstr]’
/root/symbiotic/transforms/ClassifyInstructions.cpp:111:69:   required from here
/usr/include/llvm/PassSupport.h:76:76: error: cannot convert ‘{anonymous}::ClassifyInstr*’ to ‘llvm::Pass*’ in return
   76 | template <typename PassName> Pass *callDefaultCtor() { return new PassName(); }
      |                                                                            ^