system-build.sh: avoid making copy of a ccache executable
If `which clang` resolves to `/usr/lib64/ccache/clang`, create a symlink
to this symlink.  `cp` would otherwise create a deep copy of the target,
which does not work well:

    kdudka@kdudka-f30 ~/symbiotic % install/bin/symbiotic test.c
    6.1.0-dev-llvm-8.0.0-dg:56376dd3-symbiotic:6ca31353-klee:66be91fb-sbt-slicer:0739f6e4-sbt-instrumentation:98b9452c
    cc: ccache: error: Recursive invocation (the name of the ccache binary must be "ccache")

    RESULT: ERROR (Compiling source '/home/kdudka/symbiotic/test.c' failed)
    ERROR:  == FAILURE ==
    Compiling source '/home/kdudka/symbiotic/test.c' failed